language: node_js
node_js:
script: node generate.js
# after_success:
  # - .travis/push.sh
branches:
  only:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: gh-pages