name: GenerateBlog

on: [issues]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10]
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: npx github:lotosbin/issue2blog -u lotosbin -r lotosbin.github.io
    - uses: lotosbin/github-push-action@master
      with:
        github_user: lotosbin
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
