name: CI

on: 
 schedule:
  - cron: */5 * * * *

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10]
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: npx github:lotosbin/issue2blog -u lotosbin -r lotosbin.github.io
    - uses: ad-m/github-push-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
